### ISSUE TITLE
Connect in the 840D Power Line

### ISSUE THREAD

**Issue by flaviopaulofp** [Traeger-GmbH/sinumeriknet-samples#2]
dscharnagl, Congratulations on the project carried out.
I was able to perform reading on the 840D Solution Line and 828D Solution Line.
I was not able to perform 840D Power Line, what would be the network topology for the connection to be successful? I used PCU's Port Company network.

best regards

**Comment by Tvvgge** [comment]
Hello! Sorry I can not answer your question. I'm now having a problem to connect to my NCU. I'm using 840d sl with ethernet cable connected from X127 port to my laptop. And then I typed in the X127 IP address to this command "using (var client = new SinumerikClient("s840d.sl://192.168.215.1"))". I replaced 192.168.0.80 to 192.168.215.1, but when I run the code I can't get the value from my cnc machine. Do you know what's the problem? 

All I did is open the file"SinumerikNet.Advanced.Samples.sln" and change the IP and then run the code
Since I'm new to C# so I don't really know if I did it wrong.

thank you in advance!!

**Comment by dscharnagl** [comment]
Hi flaviopaulofp,

thank you for your interest into our SDK. I'm not sure how the setup looks like with your "PCU's Port Company network". However the Powerlines X101 interface can be used to access the NCU using the S7-LAN adapter provided by Traeger (https://www.traeger.de/industrial-ethernet/s7-lan-mpi-lan.html). Just plug the adapter on the interface, connect the ethernet and you can access the Powerline in the same way as you access the Solutionline (just change the Uri.Scheme to "840d.pl").

In case of more questions: Just respond.
Kind regards

**Comment by flaviopaulofp** [comment]
> Hi flaviopaulofp,
> 
> thank you for your interest into our SDK. I'm not sure how the setup looks like with your "PCU's Port Company network". However the Powerlines X101 interface can be used to access the NCU using the S7-LAN adapter provided by Traeger (https://www.traeger.de/industrial-ethernet/s7-lan-mpi-lan.html). Just plug the adapter on the interface, connect the ethernet and you can access the Powerline in the same way as you access the Solutionline (just change the Uri.Scheme to "840d.pl").
> 
> In case of more questions: Just respond. Kind regards

**Comment by flaviopaulofp** [comment]
> 

Thank you for the informations.

I will really need this adapter to communicate!

**Comment by dscharnagl** [comment]
Hi flaviopaulofp,

you can order a quotation for the adapter via sales@traeger.de.
Please provide your companies contact data to address the quote accordingly.

Kind regards
